<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GGQ6OF8" failures="1" tests="2" name="loginTest" time="17.191" errors="0" timestamp="2024-08-30T19:30:39 IST">
  <testcase classname="com.SwagLabs.Testlayer.LoginTest" name="validatelogintest" time="0.349"/>
  <testcase classname="com.SwagLabs.Testlayer.LoginTest" name="validatelogintestwithinvalidcredntials" time="0.335">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.SwagLabs.Testlayer.LoginTest.validatelogintestwithinvalidcredntials(LoginTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- validatelogintestwithinvalidcredntials -->
</testsuite> <!-- loginTest -->
